name: Binder
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@master

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@1835b83b93ae93043d30c85210766d957df68f3f
      with:
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        BINDER_CACHE: true
        DOCKER_REGISTRY: "ghcr.io"
        IMAGE_NAME: "fmannhardt/course-applied-processmining"
